### ISSUE TITLE
BUG: Steam doesn't work

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis-winebuild#79] opened 2019-04-21 08:23 UTC
![image](https://user-images.githubusercontent.com/11302521/56467441-cba29a00-6416-11e9-932d-0b953f026ab7.png)

Mensioned window is steam that is openned if any steam application is invoked.

tested on new hitman absolution and DOOM(2016)

![image](https://user-images.githubusercontent.com/11302521/56467451-dceba680-6416-11e9-93a8-a2b34bd3d6e5.png)
![image](https://user-images.githubusercontent.com/11302521/56467466-0ad0eb00-6417-11e9-954d-ca4cc678281a.png)

To reproduce grab same commit and try to install DOOM (2016)

**Comment by qparis** [comment] 2019-04-22 09:27
Any idea on what could cause the problem?

**Comment by Kreyren** [comment] 2019-04-22 09:54
~~lack of compiling wine from source like a real man~~

based on `wine: Unhandled page fault on read access to 0x00000000 at address (nil) (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x00000000).`

On quicklook i would suspect corrupted wine build. 

checking.

**Comment by plata** [comment] 2019-04-22 11:01
There's one thing I didn't test yet and that's 64 vs 32 bits. My system Wine should be 64 bits but I tested with 32 bits Phoenicis Wine.

**Comment by plata** [comment] 2019-04-22 11:46
I've deleted my Phoenicis Wine such that it got reinstalled during the Steam installation. Now it worked.

**Comment by Kreyren** [comment] 2019-04-22 15:04
> I've deleted my Phoenicis Wine such that it got reinstalled during the Steam installation. Now it worked.

so architecture is irelevant to the issue?

**Comment by plata** [comment] 2019-04-22 18:46
Seems so, yes. Can you reproduce this behavior?

**Comment by Kreyren** [comment] 2019-04-23 07:35
> Seems so, yes. Can you reproduce this behavior?

My system wine is 64+32 bit.

Nuked ~/.Phoenicis, Installing Hitman Absolution.

it takes forever to download wine 4.6 it's +- 5 min now.

Same issue
![image](https://user-images.githubusercontent.com/11302521/56563054-bbb7c100-65a2-11e9-9677-b834087b517f.png)

**Comment by Kreyren** [comment] 2019-04-23 07:36
@plata What wine version did you use?

**Comment by Kreyren** [comment] 2019-04-23 08:02
Relevant ? https://github.com/PhoenicisOrg/scripts/pull/916

**Comment by plata** [comment] 2019-04-23 08:56
I used the Steam app (i.e. only Steam, no game). Can you try that as well? I would like to know where exactly the problem occurs.

**Comment by plata** [comment] 2019-04-23 08:58
Or could it be that you have this: https://www.playonlinux.com/en/topic-15209.html ?

**Comment by Kreyren** [comment] 2019-04-23 09:30
> I used the Steam app (i.e. only Steam, no game). Can you try that as well? I would like to know where exactly the problem occurs.

Tried steam already on 4.6 and 4.5 both staging using steam in phoenicis repo -> same issue

**Comment by Kreyren** [comment] 2019-04-23 09:34
tried 
```console
kreyren@dreamon ~ $ .Phoenicis/engines/wine/staging-linux-amd64/4.6/bin/wine Games/HitmanAbsolution/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Hitman\ Absolution/HMA.exe
```

which has same issue

Noticed `Wine cannot find the ncurses library (libncurses.so.5).` in output, please verify

whole log: http://dpaste.com/32S48HM

**Comment by plata** [comment] 2019-04-23 09:46
I have this ncurses message as well. I don't think it's related. If you want, you can open a new issue for it (in winebuild).

Please verify:
- Steam app from scripts master (with Wine upstream 4.0)
- any other app (e.g. Notepad++) to ensure that it's really Steam specific

**Comment by Kreyren** [comment] 2019-04-23 09:54
@plata 
> any other app (e.g. Notepad++) to ensure that it's really Steam specific

Note that i run HitmanAbsolution.exe from executable -> not steam specific issue -> ncurses seems very relevant. Checking

Trying phoenicis steam again, didn't install before.

**Comment by Kreyren** [comment] 2019-04-23 10:02
![image](https://user-images.githubusercontent.com/11302521/56572569-3be82180-65b7-11e9-9250-c4fbced1d318.png)


**LIBNCURSES MANDATORY!! SOLVED**

**Comment by Kreyren** [comment] 2019-04-23 10:08
EDIT: ncurses not mandatory, i'm insane

**Comment by Kreyren** [comment] 2019-04-23 10:46
Game and steam works on 4.6 staging for amd64 grabbed from phoenicis so it's probably phoenicis issue somewhere with handling the game. 

Can you exclude my installer from the issue?

**Comment by Kreyren** [comment] 2019-04-23 11:01
relevant?

```
[WARN ] org.phoenicis.javafx.views.mainwindow.installations.dto.InstallationDTO (l.56) - Installation ID (Hitman Absolution_1556017177544) contains invalid characters, will remove them.
```

**Comment by plata** [comment] 2019-04-23 15:32
No, those are not a problem.

So to summarize: If you install Steam in Phoenicis, you get the error. If you use a Phoenicis Wine build from console, it works. Is this correct?

**Comment by plata** [comment] 2019-04-23 15:33
If this is the case, it might be related to LD_LIBRARY_PATH.

**Comment by Kreyren** [comment] 2019-04-23 22:06
@plata 

> So to summarize: If you install Steam in Phoenicis, you get the error. If you use a Phoenicis Wine build from console, it works. 

Based on my test result yes, try to verify my results before confirming this info.

**Comment by plata** [comment] 2019-04-24 08:16
Ok, let me know when you have a clear view.

**Comment by Kreyren** [comment] 2019-04-24 09:28
@plata i have clean view i'm asking you to verify my results.

**Comment by plata** [comment] 2019-04-24 09:55
Sorry didn't understand that. Well, I cannot do that because I do not have this issue. What you could do is: add a print of `ldPath` to https://github.com/PhoenicisOrg/scripts/blob/a2369c341190bfbe429bcee8ebfc2431cd92dee7/Engines/Wine/Engine/Implementation/script.js#L259 and compare this with your `LD_LIBRARY_PATH` in the console where you executed Wine.

**Comment by Kreyren** [comment] 2019-04-24 10:36
@plata so you suspect it's caused by libraries provided with the engine?

**Comment by plata** [comment] 2019-04-24 10:49
Or that it doesn't use the correct ones from your OS, but yeah something in that direction.

**Comment by qparis** [comment] 2019-06-02 21:46
Should be fixed now that runtimes are supported. Ensure 32bits & 64bits freetype are installed

**Closed by qparis** 2019-06-02 21:46 UTC
Labels: bug
