### ISSUE TITLE
A request - Could you add those builds?

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [PhoenicisOrg/phoenicis-winebuild#73] opened 2019-04-01 19:37 UTC
There is a new project that builds Wine-staging-esync, and Proton builds that can be used with Playonlinux.

https://github.com/Kron4ek/Wine-Builds

Could you add these builds to your collection?

**Comment by qparis** [comment] 2019-04-01 19:38
Hi,

The project basically tries to achieve the same things (they are using chroot instead of docker). I think the best would be to merge our efforts so that we have only one project

**Comment by qparis** [comment] 2019-04-03 11:17
Why is the ticket closed?

**Comment by Kron4ek** [comment] 2019-04-03 11:24
I suppose, a proper solution is to write a Hook for applying Esync patches (like a Hook for Staging patchset). The problem is that different Wine versions requires different Esync compatibility patches (from TkGlitch repo) and future versions may require additional fixes. I mean it's not that simple as applying Staging patchset (./patchinstall.sh --all).

**Comment by qparis** [comment] 2019-04-03 11:25
What additional fixes could we anticipate?

We can also take the version from a git repository

**Comment by Kron4ek** [comment] 2019-04-03 11:50
Can't say what additional fixes will be needed in the future, i'm tracking commit history of [TkG repo](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git) to know when new additional fixes added. For example, [4.5 requires](https://github.com/Tk-Glitch/PKGBUILDS/commit/4a9f0375da66692af15f0bfdc49b1611b06771f8#diff-410db0d6d78fed0dbe64a6a4e5025e00) additional fixes, and 4.4, 3.20, 3.16 requires different fixes. [PKGBUILDS](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/PKGBUILD) can be used as a pattern.

If you don't mind using ready sources you can simplify building (and a Hook) a lot. For example, you can use sources from [Lutris repo](https://github.com/lutris/wine/tree/tkg) (tkg branch).

**Comment by qparis** [comment] 2019-04-03 12:07
As long as the version are tracked, it is easy to add a wine distribution to the builds from a source repository yep. Then the builds will automatically be compiled and hosted

**Comment by Kron4ek** [comment] 2019-04-06 13:07
Esync was added to Staging patchset 2 days ago, so there is no need in additional patches anymore.

https://github.com/wine-staging/wine-staging/commit/553986fdfb111914f793ff1487d53af022e4be19

**Comment by ahmed-elsayed2017** [comment] 2019-04-06 13:18
> Esync has been added to Staging patchset, so there is no need in additional patches anymore.
> 
> [wine-staging/wine-staging@553986f](https://github.com/wine-staging/wine-staging/commit/553986fdfb111914f793ff1487d53af022e4be19)

Good news. Thanks.

**Comment by qparis** [comment] 2019-04-06 18:09
Good news!

So I assume it is no longer necessary to consider a wine esync distribution, correct?

**Comment by Kron4ek** [comment] 2019-04-06 18:45
> So I assume it is no longer necessary to consider a wine esync distribution, correct?

Yes, Staging is enough.

**Comment by ImperatorS79** [comment] 2019-04-18 17:12
I did not see this, this is great!

**Comment by plata** [comment] 2019-04-19 10:51
So can we close this issue?

**Closed** 2019-04-19 10:55 UTC
