### ISSUE TITLE
Missing OSX dependencies

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis-winebuild#39] opened 2018-12-24 11:24 UTC
At the moment:
```
configure: QuickTime 64-bit development files not found, video decoding won't be supported.
configure: X 64-bit development files not found, the X11 driver won't be supported.
configure: libsane 64-bit development files not found, scanners won't be supported.
configure: libv4l 64-bit development files not found.
configure: libgphoto2 64-bit development files not found, digital cameras won't be supported.
configure: libgphoto2_port 64-bit development files not found, digital cameras won't be auto-detected.
configure: libpulse 64-bit development files not found or too old, Pulse won't be supported.
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.
configure: libudev 64-bit development files not found, plug and play won't be supported.
configure: libSDL2 64-bit development files not found, SDL2 won't be supported.
configure: libcapi20 64-bit development files not found, ISDN won't be supported.
configure: libgsm 64-bit development files not found, gsm 06.10 codec won't be supported.
configure: libkrb5 64-bit development files not found (or too old), Kerberos won't be supported.
configure: libgssapi_krb5 64-bit development files not found (or too old), no Kerberos SSP support.
configure: openal-soft 64-bit development files not found (or too old), XAudio2 won't be supported.
```
Some of them have a macport, but the builder fails with error 404 when trying to install them, which is strange since they exist.

**Comment by Gcenx** [comment] 2018-12-24 16:00
You can ignore QuickTime that also happens for me even with the QuickTime.framework added to my build environment.

Afew others also can be ignored but seeing that many does not seem correct, I will try looking over linux-x86-wine_osxcross more when I’m in front of my system as I see somethings I believe are incorrect or could be optimized

**Comment by ImperatorS79** [comment] 2018-12-24 16:13
I think the QuickTime one is particularly important since it is a dependency which appears only on macOS.

**Comment by Gcenx** [comment] 2018-12-24 16:41
> I think the QuickTime one is particularly important since it is a dependency which appears only on macOS.

You will always get that error on 64Bit build even if the 10.8SDK is used after that the QuickTime.framework was removed.

On Linux I don’t think it even checks for QuickTime support.

**Comment by ImperatorS79** [comment] 2018-12-24 16:42
That was my point : QuickTime is not a dependency on linux, only on macos

**Comment by Gcenx** [comment] 2018-12-24 16:53
> That was my point : QuickTime is not a dependency on linux, only on macos

I understand but that’s how it is I’m afraid, even the offical winehq builds don’t have QuickTime support within wine64 only within wine.

But really it makes little difference the QuickTime support from that framework is very old Apple them selves depreciated it.

If that’s something that’s going to really bother anyone I can explain how to get the QuickTime working in at least wine even when using the 10.11SDK to build

**Comment by Gcenx** [comment] 2018-12-30 22:05
I tried to add additional dependancies to download via _osxcross-macports_ but it fails to find them yet I can find on http://packages.macports.org/ like [libsdl2](http://packages.macports.org/libsdl2/)

For now can we not just download the missing packages directly and add them so they can be used?

**Comment by qparis** [comment] 2018-12-30 23:33
osxcross-macports -m32 libsdl2 ?

**Comment by Gcenx** [comment] 2018-12-30 23:47
> osxcross-macports -m32 libsdl2 ?

`osxcross-macports -32 install libsdl2`
Same format as the other commands, strange part is it does find libsdl just not libsdl2.

**Comment by qparis** [comment] 2018-12-30 23:55
What you can do is run “docker container run -it <image_id>”

It will start a container from an image so that you can try the commands inside to debug.

Also, it is maybe because libsdl2 is not available for all macOS version

**Comment by Gcenx** [comment] 2018-12-31 17:03
> How does it work? Is the library statically linked?

What part are you asking about?

**Comment by Gcenx** [comment] 2019-01-01 14:44
> libsdl2 no needed at runtime

For wine/staging/CrossOver you need libsdl2 at compile time for controller support. (xinput)
Proton needs libsdl2 at all times.

Currently this has no libsdl2 so controller support is avalaibe via xinput in games without workarounds. The problem is macports only have split dylibs not a single universal one, so the choose is;
- build a universal libsdl2 from source
- download both versions then lipo them into a universal version


Also currently all dylibs that are download are only 32bit when it really needs to be universal since the same image is used for 32bit and 64Bit builds.

**Comment by qparis** [comment] 2019-01-01 14:44
In fact they are universal if you look well

**Comment by Gcenx** [comment] 2019-01-01 14:53
> In fact they are universal if you look well

I’m not near my system currently but if that’s true why is @ImperatorS79 getting the X11 development files missing? (Unless they read the first pass when build winetools)

**Comment by qparis** [comment] 2019-01-01 14:54
XQuartz is not installed in the build machine. Do we need X11Drv?

**Comment by Gcenx** [comment] 2019-01-01 14:59
> XQuartz is not installed in the build machine. Do we need X11Drv?

Ah yes your calling wine not wine +X11. (Not sure if the macports wrapper can handle that)
Depends I will be adding that since I would want X11Drv.

**Comment by qparis** [comment] 2019-01-01 15:00
It's find to have them. However, I think it will be tricky to bundle XQuartz

**Comment by Gcenx** [comment] 2019-01-01 15:02
> It's find to have them. However, I think it will be tricky to bundle XQuartz

Hum that’s true we did remove the bundled XQuartz from Wineskin as it was hell to keep it working....
Hum maybe don’t add it as it will increase the libs that will be bundled with the wine builds.

**Comment by qparis** [comment] 2019-01-01 15:07
I think we are find to have the errors, because it makes transparent to the users what are inside the builds when they read the logs

**Comment by Gcenx** [comment] 2019-01-01 16:02
> I think we are find to have the errors, because it makes transparent to the users what are inside the builds when they read the logs

I agree but maybe disable the Linux related ones like pulse and oss etc so the log only had macOS related missing dependancies showing?

So ignore X11 it’s openal-soft and libsdl that should be fixed.

**Comment by qparis** [comment] 2019-01-01 16:03
That could make sense yes

**Comment by ImperatorS79** [comment] 2019-01-02 12:06
Is not the quartz-vm macport enough to install xquartz ?

**Comment by Gcenx** [comment] 2019-01-02 13:54
> Is not the quartz-vm macport enough to install xquartz ?

No the packages include with wine-devel will work with some slight changes;

```
configure: QuickTime 64-bit development files not found, video decoding won't be supported.
configure: libva 64-bit development files not found, GPU video acceleration won't be supported.
configure: lib(n)curses 64-bit development files not found, curses won't be supported.
configure: libsane 64-bit development files not found, scanners won't be supported.
configure: libv4l 64-bit development files not found.
configure: libgphoto2 64-bit development files not found, digital cameras won't be supported.
configure: libgphoto2_port 64-bit development files not found, digital cameras won't be auto-detected.
configure: GTK3 64-bit development files not found, GTK themes won't be supported.
configure: libpulse 64-bit development files not found or too old, Pulse won't be supported.
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.
configure: libudev 64-bit development files not found, plug and play won't be supported.
configure: libcapi20 64-bit development files not found, ISDN won't be supported.
configure: libgsm 64-bit development files not found, gsm 06.10 codec won't be supported.
configure: libkrb5 64-bit development files not found (or too old), Kerberos won't be supported.
configure: libgssapi_krb5 64-bit development files not found (or too old), no Kerberos SSP support.
configure: libavcodec 64-bit development files not found (or too old), XAudio2 WMA conversion won't be supported.
```

I didn't suppress any of the errors for the moment, ncurses needs to build 64bit then be merged to be a universal dylib as currently it's only 32bit.
I install libsdl2 then copy in a premade universal libsdl2 (need to change to compile from source instead but I was lazy)

> Edit: the osxcross environment is trying to copy the macOS SDK v11, but there is only the v8 one in the repo

The repo is not really even meant to include the current SDK to avoid potential legal issues

**Comment by ImperatorS79** [comment] 2019-01-02 14:09
It's just that before i could experiment the osxcross build because it was using the 10.8 sdk.

> No the packages include with wine-devel will work with some slight changes;

I do not understand what you mean here.

**Comment by Gcenx** [comment] 2019-01-02 14:18
> It's just that before i could experiment with the osxcross build because it was using the 10.8 sdk.

Yeah I get it, but to build vulkan support that SDK was needed, but you can download the SDK from another GitHub page if you don’t have a Mac.

> > No the packages include with wine-devel will work with some slight changes;
> 
> I do not understand what you mean here.

I was rushing to work (in transit now) but I changed the current osxcross-macports commands so acomplish the results I posted. When I have finished the needed changes including building from source I will do a pull-request.

**Comment by ImperatorS79** [comment] 2019-01-04 13:51
@Gcenx details, but you can maybe try to download libgsm from brew -> [https://homebrew.bintray.com/bottles/libgsm-1.0.18.el_capitan.bottle.tar.gz"](https://homebrew.bintray.com/bottles/libgsm-1.0.18.el_capitan.bottle.tar.gz) and try to install it yourself ^^.

**Comment by Gcenx** [comment] 2019-01-04 14:52
> > @qparis would you rather wait until I have finished adding mpg123 and ffmpeg or would you rather me clean up what I currently have?
> 
> As you prefer :)

Ok let me see what else I can get done before a pull-request.

> @Gcenx details, but you can maybe try to download libgsm from brew -> [https://homebrew.bintray.com/bottles/libgsm-1.0.18.el_capitan.bottle.tar.gz"](https://homebrew.bintray.com/bottles/libgsm-1.0.18.el_capitan.bottle.tar.gz) and try to install it yourself ^^.

It’s not really needed plus homebrew packages are x86_64 only so it won’t be useful, it would be better to just compile it from source then merge the results into a universal item, just like it now does for NCurses.

The last major items to add for macOS now are mpg123, ffmpeg & FAudio.
FAudio is more for future 4.x but if we already have the requirments of sdl2 and ffmpeg then why not.

**Comment by Gcenx** [comment] 2019-01-25 03:00
#61 Will deal with SDL2

**Comment by Gcenx** [comment] 2019-05-28 17:32
@qparis & @ImperatorS79 now with #89 & #90 this project now provides builds that are better then Winehq!

The remaining items are;
- Gnutls (that won’t break Wine) < My current priority 
- mpg123 (mp3 audio decoding)
- gsm (gsm audio encoding/decoding)
- ffmpeg with wma support (needed for FAudio to support wma audio)

The thing is ffmpeg with wma decoding could cause legal issues since we end up distributing a precompiled version. So while it’s possible should we?

**Comment by qparis** [comment] 2019-05-28 22:05
This is great. 
Concerning wma decoding, what does it depend on? We need to check but I think it is legal in Europe. If this is the case, we could distribute two separate distributions

**Comment by qparis** [comment] 2019-05-28 22:05
(By the way, congratulations)

**Comment by Gcenx** [comment] 2019-05-29 00:35
I'm not sure on the exact licensing but I know it was brought up on [FAudio Github](https://github.com/FNA-XNA/FAudio/issues/32)

I'm also not sure on the legality of it in Europe it's been over 10 years since I moved to USA, but you might want to investigate to be on the safe side.

Winetricks is grabbing mingw compiled dll files from [FAudio Builds](https://github.com/Kron4ek/FAudio-Builds) that's a workaround for both cases

**Comment by ImperatorS79** [comment] 2019-06-05 09:43
@qparis For darwin, are you still packaging the dependencies inside each wine version, or is it a runtime (I hope for space consideration) ? So that I could modify the runtime code accordingly.

**Comment by qparis** [comment] 2019-06-05 09:50
For the moment, dependencies are packaged because of POLv4.
POLv5 supports the runtime

**Comment by ImperatorS79** [comment] 2019-06-05 09:55
Okay, so no need for the runtime installation currently.

**Comment by qparis** [comment] 2019-06-05 09:57
Still, let's keep it so that we are compatible with standalone and non-standalone builds

**Comment by Gcenx** [comment] 2019-06-06 02:19
As I needed to add cmake to compile the latest version of osxcross I also updated FAudio to 19.06 and made the change to no longer patch .so files.

I left alone the bundling of dylib's since you said POM4 doesn't support the runtime usage yet.

**Comment by Gcenx** [comment] 2019-09-02 03:09
@qparis well seems I need to do some more updating to compile Wine-4.15, would you like it done within another branch and do a pull-request?

Also the SDK will need to be upgraded to 10.13,

**Comment by qparis** [comment] 2019-09-02 06:27
Yeah you can go ahead :-)

**Comment by Gcenx** [comment] 2020-05-20 14:24
@qparis do we really need VKD3D enabled considering it’s basically useless on macOS as MoltenVK doesn’t have the required extensions let alone the newer branch of VKD3D that’s being used within Proton.

I’d also like to know what you think of #121 as FAudio will be locked for 20.03 on macOS unless we drop 10.8 support.

I’d like clarification on these before finalizing all my recent changes/cleanup

**Comment by qparis** [comment] 2020-05-21 14:57
I don't know if it is required or not in fact. If you think we can remove it, let's go ahead :) 
Do you think we still need 10.8 support?

**Comment by Gcenx** [comment] 2020-05-21 15:24
I won’t remove the VKD3D related stuff just disable it as it’s possible it will become useful later.

Not really less then 1% will be using 10.8 and honestly it’s going to cause more support related issues when there unable to access any secured services, to continue supporting also means forcing your own services to allow a much older insecure version of TLS (1.0)

I’ll move the minimum deployment target to 10.9 that’s the lowest target I’ve been able to still access secured connections including GitHub using curl/git

**Comment by Gcenx** [comment] 2020-05-23 22:29
@qparis there I've done with the improvements see #123

**Comment by qparis** [comment] 2021-08-10 19:47
Fixed

**Closed by qparis** 2021-08-10 19:47 UTC
Labels: darwin

**Comment by Gcenx** [comment] 2021-08-10 20:25
@qparis we still require mpg123, recently upstream removed some macOS only code meaning it’s now required for macOS.
