### ISSUE TITLE
Abstract: Maintainance of eSync patchset

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis-winebuild#57] opened 2019-01-05 23:44 UTC
Based on available informations i've understand that esync patches for WINE has the ability to increase the game performance in a scenario where wineserver is pegging a core. (seemingly case for OverWatch and possible other wineapps) 

I was told that ZF (Maintainer of esync patchset) is not willing to maintain the patchset excluding rebasing, but that he's aware of a fixes to make the patchset working. (NOT VERIFIED, WILL BE VERIFIED BASED ON RESPONSE)

If that's the case are we willing to help with the maintainance? In theory Lutris and Winehackers might be also interested in this cooperation. 

Patchset is fork of wine written in C.
https://github.com/zfigura/wine

Relevant: https://bugs.gentoo.org/674552

Relevant: https://github.com/bobwya/bobwya/tree/master/app-emulation (Has esync patches, was told that it breaks lots of things)

**Comment by ImperatorS79** [comment] 2019-01-06 11:31
AFAIK, the esync patcheset comes originally from [https://github.com/zfigura/wine/tree/esync](https://github.com/zfigura/wine/tree/esync). There is no tags associated with different wine-version in this repository. 

Additionnaly, there is [https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git/wine-tkg-patches](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git/wine-tkg-patches) (a lot used by the community), which contains patch to apply esync on top of wine-staging. However, you have to "manually" check which patch you need to apply on top of which wine-staging version :/  (r1, r2, r3, ...)(and I do not know which parts in this are required).

**Comment by madoar** [comment] 2019-01-06 19:32
I'm not very knowledgeable about wine.
I just would suggest to not add too many different distributions.
When looking at our current engines tab it is already confusing with the current number of tabs.

**Comment by qparis** [comment] 2019-01-06 19:32
This is a UI problem, not a number of distribution problem I guess.

**Comment by madoar** [comment] 2019-01-06 19:35
I don't think so. I agree it's nice for developers to have a huge number of distributions available, but it is annoying for normal users who just want to install an engine and have no in-depth knowledge about the details of the different categories.

If we can't solve the problem differently (for example through a verb), then I have no problem with adding an additional engine category.
We should just be sure that it is absolutely required to prevent cluttering (my opinion).

**Comment by qparis** [comment] 2019-01-06 19:37
Maybe we could create a phoenicis distribution that contains different patchs then

**Comment by ImperatorS79** [comment] 2019-01-06 20:19
I think it is really a UI problem. You only have:
-upstream
-staging
-proton (basically upstream (not latest) + esync + DXVK + other patches)
-dosbox
-cx (is it really needed for a normal user ?)

**Comment by ImperatorS79** [comment] 2019-01-06 20:32
This is just a repo full of a lot of patchsets which are not in wine/wine-staging. A lot of them are outdated ; and/or interesting like e.g. PBA (which seems, for some games and high OpenGL version, to increase performace of the d3d11->opengl), but it is really unmaintained by his author (and full of bugs), and meaningless now that there is DXVK. I have only mentioned it because it contains the esync patchset as a .patch .

**Comment by qparis** [comment] 2019-01-06 20:45
Do we want to maintain a repository that contains patchset, like wine staging does?

**Comment by Kreyren** [comment] 2019-01-06 21:31
@qparis why is it not acceptable to build esync from bobwya's or practically you can build them from ZF assuming that bobwya didn't do any black witchery to his ebuilds

**Comment by qparis** [comment] 2019-01-06 21:32
The problem is not to build wine, the problem is to make phoenicis-winebuild able to build it for any version of wine (or decide that we don't want to build it for all version of wine). 
The other problem is to decide about the criteria to accept to add a new supported wine distribution

**Comment by ImperatorS79** [comment] 2019-01-06 21:46
We could provide a wine-staging + esync, in place of wine-staging (since you still need WINEESYNC=1 to use the esync patchset, it will make no difference for regular use). The only remaining problem is to rebase the esync patch for each wine version (as .patch like in tkg, so that you apply it on top of wine-staging).

**Comment by qparis** [comment] 2019-01-06 21:46
I don't think we should stop providing wine-staging alone. This distribution is accepted and maintained by the wine team and the release cycle is very reliable

**Comment by ImperatorS79** [comment] 2019-01-06 21:48
Yes, but adding esync on top of it will not change that, prevent you to store another distribution, and do not change anything for regular use since you need "WINEESYNC=1" to activate the patchset.

**Comment by qparis** [comment] 2019-01-06 21:49
It will, because we won't be able to release wine-staging every two weak if we do that

**Comment by ImperatorS79** [comment] 2019-01-06 21:50
You just need to ensure that the esync patchset apply cleanly.

**Comment by qparis** [comment] 2019-01-06 21:50
There is a large chance that it is not compatible with every release.

**Comment by ImperatorS79** [comment] 2019-01-06 21:54
It seems @Tk-Glitch is really fast at doing the rebase.
If the patch does not cleanly apply, you can still build wine without it.

But I agree everything would be simpler if the esync patchset was in wine-staging (which I do not understand ^^).

**Comment by qparis** [comment] 2019-01-06 21:56
Yes, @Tk-Glitch is probably doing amazing job, but we cannot make our process rely on one person.

> But I agree everything would be simpler if the esync patchset was in wine-staging directly (which I do not understand ^^).

This is one more reason not to add in our staging builds. Wine team must have a good reason. 

I would suggest to create one last ehanced distribution with all the patch required. @madoar What do you think?

**Comment by ImperatorS79** [comment] 2019-01-06 22:04
[https://github.com/zfigura/wine/issues/18](https://github.com/zfigura/wine/issues/18) Seems to be more a reason of coding style than something really problematic. Again since you need an environment variable to use it, there is no worries.

Adding a whole new distribution just for something cosmetic like this seems quite bad for me. If the wine-staging + esync way I proposed is not an option (which I understand perfectly), I think the best way is to not do anything.

**Comment by qparis** [comment] 2019-01-06 22:05
If you read the comment, this is not just cosmetic. 

`There are some aspects of the design of these patches (namely, use of shared memory) and of their functionality (namely, that PulseEvent() and wait-all can't quite work right) that won't be acceptable upstream. As such I am afraid the patchset will always have to remain out-of-tree.`

**Comment by ImperatorS79** [comment] 2019-01-06 22:08
If you read it, you see it seems just because what is doing this patchset is not an acceptable solution in the way wine devs want solutions. But this not something like "IF you add this patchset, there is a chance everything will explode!" ^^. Remember wine still use pure ANSI C.

I mean cosmetic for the fact that Proton has esync.

**Comment by qparis** [comment] 2019-01-06 22:12
Wine is one of the most outstanding example of app in term of development process, quality of code / product and reverse engineering that I know. I really trust their point of view in that matter. 
In addition, when people will install POL staging versions, it will not really be a "wine staging", so it can be misleading for them when they receive bugs from our users. 

On the other hand I believe that this patch is very useful. This is why I would suggest to have a separate distribution

**Comment by ImperatorS79** [comment] 2019-01-06 22:13
I perfectly understand that.

**Comment by qparis** [comment] 2019-01-06 22:17
We just need to circle back with @madoar and we are good to go

**Comment by Kreyren** [comment] 2019-01-06 22:46
Too much text for me to read through atm, lets wait for the results of my research first or try to verify for yourself so that we have more info to base the decision on.

**Comment by ImperatorS79** [comment] 2019-01-06 22:48
Yes, but the repo of zfigura does not have proper tags :/ so that it is difficult to have a specific wine version.

**Comment by Kreyren** [comment] 2019-01-06 23:14
@ImperatorS79 bobwya has proper tags afaik https://github.com/bobwya/bobwya/tree/master/app-emulation

well at least to gentoo's standarts

**Comment by Tk-Glitch** [comment] 2019-01-07 05:49
I'd like to say I'm fast at rebasing also thanks to ZF's direct help and reactivity on bugfixing. Since I'm providing wine builds sources for Lutris, receiving active support from him is a game changer for the "safety" side of things. But yeah, there is no guarantee that will last forever.

Also PBA patchset is encountering huge regression since 3.20 and would require a rewrite that, so far, nobody has done.

**Comment by Kreyren** [comment] 2019-01-07 06:47
@Tk-Glitch Can you recommend an esync wine build for overwatch for me to test?

btw. thanks for your feedback it's appreciated ^^

**Comment by Tk-Glitch** [comment] 2019-01-07 07:13
@Kreyren I don't think there's a need for anything fancy regarding OW, so the basic "tkg" build available through Lutris would probably be my default pick. If you want a bit fancier, the protonified build will give you additional fullscreen hacks for scaling and compositor auto-turnoff. Also, 4.0rc's have been slightly slower than 3.21 (probably one of the reason why Strider didn't yet build 4.0rc based -tkg builds). If you got an Arch/Arch-based system around, building an optimized build from my PKGBUILD would give an additional perf boost.

About PBA regression, I can point to https://github.com/Tk-Glitch/PKGBUILDS/issues/49 as a base of work. I didn't dive into the code since november and I have to admit I have lost track of the issues with it as they were stacking and snowballing. There has been quite a bit of refactoring upstream and the first problems came with 3.17. Bobwya has made an additional patch and cleaned up the patchset for 3.17 & 3.18 but anything past that is basically broken. Firerat also opened an issue for it : https://github.com/Firerat/wine-pba/issues/3

**Comment by Tk-Glitch** [comment] 2019-01-07 07:56
I'm not using Strider builds either tbh :smile:

The regression only affects wined3d. DXVK, vkd3d and Gallium9 are unaffected.

**Comment by Kreyren** [comment] 2019-01-07 08:04
@Tk-Glitch Noted, DXVK + esync + staging + WINE 3.19-p1 still has freezes, but the performance is much better in comparison to esync less wine. Trying to tweak dlls now will try PBA after. ^^

**Comment by Tk-Glitch** [comment] 2019-01-07 08:06
Freezes? Sounds like shader/pipeline compilation to me. That should clear up by itself after a while playing.

**Comment by Kreyren** [comment] 2019-01-07 08:07
@Tk-Glitch clean up by itself? More info how?

**Comment by Tk-Glitch** [comment] 2019-01-07 08:19
@Kreyren 
There are two major sources of stutter/freeze (highly CPU and GPU driver dependent).
First, DXVK creates a state cache to restore pipelines that have already been compiled at least once, so you'll stutter/freeze on first compilation then it'll smooth itself out.
Second is shader compilation. The d3d11 shaders of your game have to be recompiled as SPIR-V by DXVK so Vulkan can use them. This can only be done on the fly when a new shader is encountered, so compilation will once again make your game stutter/freeze (RADV is much slower at that than nv's proprietary blobs btw) but also in this case, a cache will be created by your GPU driver to store the resulting SPIR-V shaders.

Overwatch is especially bad on both sides from what I know, and will create a MASSIVE amount of both pipelines and shaders, so it might take quite a few games on all maps to get a smooth experience.

**Comment by Kreyren** [comment] 2019-01-07 08:47
@ImperatorS79 Noted, no need to PBA atm then, would probably fix the issue on dishonored tho..

**Comment by Tk-Glitch** [comment] 2019-01-07 09:17
I think Dishonored 2 is the absolute wort case of pipeline creation for DXVK. When the state cache wasn't yet functional, it took minutes of mostly freezing and stutters on a 2700X before getting a complete scene rendered.

Anyway, yeah, PBA doesn't interact with DXVK and only affects wined3d, as noted above.

**Comment by Kreyren** [comment] 2019-01-07 09:22
@Tk-Glitch The issue on Dishonored 2 is that it's affected by DXVK regression https://github.com/ValveSoftware/Proton/issues/823 atm -> PBA might help with the issue (also a POL/Phoenicis script that i'm working on)

**Comment by Tk-Glitch** [comment] 2019-01-07 09:34
Are you sure it's DXVK and not RADV or LLVM? Vulkan support on Pitcairn is kinda meh to begin with, but you're also using LLVM 7.0.1 (which is broken). And since shader compilation is done by LLVM.. You see where I'm going.

**Comment by Kreyren** [comment] 2019-01-07 09:38
@Tk-Glitch Will check thanks for info.

**Comment by ImperatorS79** [comment] 2019-01-07 17:31
@qparis There is no Proton 64 bits in the engine tab ^^.

**Comment by plata** [comment] 2019-01-07 17:55
Just my few thoughts:
1. We should not maintain Wine patches/a separate Wine distribution unless this can be done fully automatically. It's not our core business, we have other work to do.
2. If Proton already contains esync, everybody in need of esync can use Proton.
3. Apparently Overwatch (which was the initial reason for this request) runs very well without esync.

**Comment by Tk-Glitch** [comment] 2019-01-07 19:02
Overwatch isn't exactly synchronization intensive, so esync will only help corner cases like very slow CPUs or unusually high core count CPUs. If that is all it's about, this is pretty much worthless indeed.

**Comment by LinLo** [comment] 2019-01-10 18:38
Maybe I'm wrong but "wine pba" seems to only work with direct3d9.
Unfortunately implementation is broken since wine 3.19.
> https://github.com/acomminos/wine-pba/issues/67#issue-382250387

**Comment by Kreyren** [comment] 2019-01-10 19:35
@LinLo will test, thanks for info

**Comment by KonomiKitten** [comment] 2019-01-17 13:10
@LinLo I'm not sure if that is true I use 3.16 with PBA to play WoW which uses DirectX 11 and I notice a frame rate improvement with PBA.

**Comment by KonomiKitten** [comment] 2019-01-17 14:41
@Kreyren from my testing PBA has the same performance as DXVK with World of Warcraft, and for another game Guild Wars 2 it does better than DXVK because it's DirectX 9 which DXVK does not work for.

Overall for game coverage on Wine when you have a Nvidia card PBA is superior to DXVK from my experience.

**Comment by Kreyren** [comment] 2019-01-17 15:01
@KonomiKitten Interesting, thanks for info will test.

**Comment by ImperatorS79** [comment] 2019-01-17 15:21
You will "soon" be able to test gallium 9 for d3d9 with a simple verb, so that you could test performance of PBA vs gallium 9 ;-).

**Comment by Kreyren** [comment] 2019-01-17 15:31
@ImperatorS79 I have both pba and gallium9 on my system, but i didn't have time to test them yet >.>

**Comment by Tk-Glitch** [comment] 2019-01-18 11:36
PBA is only faster when the CPU overhead implied by DXVK is a limiting factor (or if your GPU's Vulkan drivers are bad). If your CPU is fast enough, DXVK will be faster.

**Comment by Kreyren** [comment] 2019-01-18 16:52
@Tk-Glitch Helpfun, thanks

**Comment by ImperatorS79** [comment] 2019-04-18 17:13
Is this still relevant since the info from #73 ?

**Comment by Kreyren** [comment] 2019-04-19 05:20
@ImperatorS79 based on info provided i would still argue to honor GNU ehics and support esync assuming low maintainance and that it can be applied on demand.

**Comment by Tk-Glitch** [comment] 2019-04-19 07:03
As long as staging builds are provided, esync will be included now. It's disabled by default anyway and requires the use of an env var toggle. The "maintainance" of it is now the responsibility of wine-staging devs.

**Comment by ImperatorS79** [comment] 2019-04-19 07:16
Which was the best solution as stated earlier in this issue. I will close this then.

**Closed by ImperatorS79** 2019-04-19 07:16 UTC

**Comment by Kreyren** [comment] 2019-04-20 09:37
Perfect o.o
